<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>aml</string>
		<string>AML</string>
	</array>
	<key>name</key>
	<string>AML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Keys and values</string>
			<key>match</key>
			<string>^(?i)\s*(\w|-)+\s*:</string>
			<key>name</key>
			<string>entity.name.tag.aml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Nested key structure</string>
			<key>match</key>
			<string>^\s*(?i)((\w+|-)+\.)+(\w+|-)+\s*:</string>
			<key>name</key>
			<string>variable.parameter.aml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?i)(\{\s*(\w+|-|\.)+\s*\})</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.aml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Nested key structure with an object block</string>
			<key>end</key>
			<string>^(\{\}|(?=\{.+\}))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.aml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?i)(\[\.*(\w+|-|\.)+\s*\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.aml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Array of objects</string>
			<key>end</key>
			<string>^(\[\]|(?=\[(?:\.\]).+\]))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.aml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Arrays of strings</string>
					<key>match</key>
					<string>^\s*\*.+</string>
					<key>name</key>
					<string>string.quoted.double.aml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?i)(\[\+(\w+|-|\.)+\s*\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.aml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Freeform arrays</string>
			<key>end</key>
			<string>^(\[\]|(?=\[\+.+\]))</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.aml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Multi-line values</string>
			<key>match</key>
			<string>^:end</string>
			<key>name</key>
			<string>constant.language.aml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Escape characters</string>
			<key>match</key>
			<string>(\\)(\S)+</string>
			<key>name</key>
			<string>constant.character.escape.aml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^:skip</string>
			<key>comment</key>
			<string>Block comments</string>
			<key>end</key>
			<string>^:endskip</string>
			<key>name</key>
			<string>comment.block.aml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^:ignore</string>
			<key>comment</key>
			<string>Ignore comments</string>
			<key>end</key>
			<string>^:endignore</string>
			<key>name</key>
			<string>comment.block.aml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.aml</string>
	<key>uuid</key>
	<string>48d64183-3530-4807-9398-8b223de13788</string>
</dict>
</plist>
